name: E2E-test-dApp CI integration
on:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Linting using Eslint
        run: |
          npm run lint
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'CI: Linted files'
          commit_options: '--no-verify'
      - name: Formatting using Prettier
        run: |
          npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'CI: Formatted files'
          commit_options: '--no-verify'
